Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using InfoCelEletronic.Models;




    namespace InfoCelEletronic.Controllers
{

    public class ServicosController:Controller
    {



        public IActionResult Servicos(){
            return View();
        }

        
         public IActionResult cadastrarOrcamento(){
                Autenticacao.CheckLogin(this);
        return View();
        }

[HttpPost]
          public IActionResult cadastrarOrcamento(servicos serv){
              servicosServicos sr = new servicosServicos();
              sr.cadastrarServico(serv);
              

        return View();
        }

         

        public IActionResult listarservicos(){
                     
                   
                      servicosServicos ss=new servicosServicos();
                      
                      int tipo = Convert.ToInt32(HttpContext.Session.GetInt32("tipo"));          
                      if(tipo == 0){
                          List<servicos> servicosEncontrados = ss.listarServicos();
                             return View(servicosEncontrados);    
                      }else{
                            int ID = Convert.ToInt32(HttpContext.Session.GetInt32("IdCliente"));
                          //List<servicos>servE = new List<servicos>();
                          

                           return View(ss.listServicoID(ID)); 
                      }
                    }  

       
            
        
        

        public IActionResult atualizaservico(int Id){
            
            servicosServicos ss= new servicosServicos();
            servicos encontrado= ss.obterPorId(Id);
            return View(encontrado);
        }

        [HttpPost]
          public IActionResult atualizaservico(servicos atualizar){
            servicosServicos ss= new servicosServicos();
            ss.atualizarServico(atualizar);
            return RedirectToAction("listarservicos");
        }
        
    public IActionResult excluirservico(int id){
        servicosServicos ss = new servicosServicos();
        ss.deletServicos(id);
        return RedirectToAction("listarservicos");

    }
    
    
    }
}

Controllers/clienteController.cs
using System.Net.Http;
using System.Security.Cryptography;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using InfoCelEletronic.Models;

namespace InfoCelEletronic.Controllers
{
    public class clienteController:Controller
    {
        
        public IActionResult CadastroCliente(){
         
             
            return View();
        }

        
[HttpPost]
         public IActionResult CadastroCliente( cliente c){

            clienteServico cs = new clienteServico();   
                c.Tipo = cliente.usuarioPADRAO;
                 cs.cadastro(c);
                     ViewData["msg"]= "cadastro realizado com sucesso";
                        
            return RedirectToAction("LoginCliente");
        }

         public IActionResult LoginCliente(){

                 return View();
        }

[HttpPost]
        public IActionResult LoginCliente(string login, string senha){
             if(Autenticacao.verificaLoginSenha(login,senha,this)){
                    return RedirectToAction("Index","Home");
            }else{
                 ViewData["Erro"] = "Senha, ou o nome de usuario está invalido!!";
                return View();

            }
        }
        

       


        public IActionResult ListarCliente(){
            //Autenticacao.verificaSeUsuarioAdmin(this); 
            clienteServico cs = new clienteServico();
           
           int tipo = Convert.ToInt32(HttpContext.Session.GetInt32("tipo")); 
            
            if(tipo==0){ // se o tipo for 0 o usuario é adm, e a listagem vem completa
                List<cliente> listaCliente = cs.listarCliente();
                
            return View(listaCliente);
            }else{ // se não: o tipo usuario não for 0, so pode ser 1, que significa que o usuario é padrão e não tem previlegios adm e
                   // a listagem sera feita usando o id do usuario, para listar somente o que o usuario cadastrou 
                int ID = Convert.ToInt32(HttpContext.Session.GetInt32("IdCliente"));
                  List<cliente> listaCliente = new List<cliente>();
                  listaCliente = cs.listClieID(ID);
                
                return View(listaCliente);
            }
            
         }
            
        
           public IActionResult AtualizarCliente(int id){
            cliente clienteEncontradoPorID = new clienteServico().ListarPorID(id);
            return View(clienteEncontradoPorID);
        }


        [HttpPost]
                public IActionResult AtualizarCliente(cliente clieUpdate){
                     clienteServico cs = new clienteServico();  
                    
                     cs.editarCliente(clieUpdate);
                     ViewData["msg"]= "dados atualizados com sucesso";
                     return RedirectToAction("ListarCliente");
        }


        public IActionResult excluirClirente(int id){
            clienteServico cs = new clienteServico();
            cs.DeletCliente(id);
            return RedirectToAction("ListarCliente");
        }

        
            public IActionResult logOut(){
                 HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");

            }




      

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InfoCelEletronic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background:#2F4F4F;">
    <div class="container-fluid ">



        <div class="row   p-5" style="background:#008080;">





            <div class="col-sm-12  col-md-12  col-lg-12 nav justify-content-center   ">








                <!--***********************************************************************************************************************-->



                <nav class="navbar navbar-expand-lg navbar-light   ">

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"> </span>
                    </button>







                    <div class="collapse navbar-collapse" id="navbarNav">



                        <ul class="navbar-nav text-center nav nav-pills nav-fill  font-weight "
                            style="font-size: 18px ; text-shadow:1px 1px 2px  black;">



                            <li class="nav-item active mr-1">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home"
                                    asp-action="Index">Home</a>
                            </li>


                            <li class="nav-item mr-1">
                                <a class="nav-link text-light" asp-area="" asp-controller="Servicos"
                                    asp-action="Servicos">Serviços</a>
                            </li>


                            <li class="nav-item mr-1">
                                <a class="nav-link text-light" asp-area="" asp-controller="cliente"
                                    asp-action="CadastroCliente">Cadastro</a>
                            </li>




                            <!--*******************************************************ADM***************************************************************-->
                          

                              
                                    <li class="nav-item mr-1">
                                        <a class="nav-link text-light" asp-area="" asp-controller="cliente"
                                    asp-action="LoginCliente">Login</a>
                                    </li>

                               


                                    <li class="nav-item mr-1">
                                        <a class="nav-link text-light" asp-area="" asp-controller="cliente"
                                    asp-action="ListarCliente">Clientes</a>
                                    </li>

                                    <li class="nav-item mr-1">
                                        <a class="nav-link text-light" asp-area="" asp-controller="cliente"
                                    asp-action="logOut">Sair</a>
                                    </li>







                                    <li class="nav-item mr-1">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Servicos"
                                    asp-action="listarservicos">listar serviços</a>
                                    </li>
                                    <li>

                                       
                                    </li>
                              


                          
                               



                               


                               

                                    
                                


                           

                        </ul>

                    </div>




                </nav>



            </div>
            <!--fecha col-->

        </div>
        <!--fecha row-->









        <div class=" row " style="background:#2F4F4F; ">
            <div class="col-12">
                <main role="main" class="mb-3">
                    @RenderBody()
                </main>
            </div>

        </div>



    </div>
    <div class="container-fluid footer border" style="background:#008080;">
        <div class="row ">
            <div class="col-sm-12 col-md-12 col-ag-12 ">
                <footer class=" text-center   " >
                    <!-- Copyright -->
                    <div>
                        &copy; 2022 - InfoCelEletronics - <a asp-area="" asp-controller="Home"
                            asp-action="Index">Home</a>
                    </div>
                    <!-- Copyright -->
                </footer>
            </div>
        </div>
    </div>











    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>